import type { Metadata } from "next";
import style from "./globals.module.scss";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html className={style.global} lang="en">
			<body>{children}</body>
		</html>
	);
}
